VSCodium (1.100.2, undefined, desktop)
Jupyter Extension Version: 2025.4.1.
Python Extension Version: 2025.4.0.
Pylance Extension not installed.
Platform: linux (x64).
Home = /home/dimgerasimou
Temp Storage folder ~/.config/VSCodium/User/globalStorage/ms-toolsai.jupyter/version-2025.4.1
Workspace folder ~/Numerical_Analysis
22:01:07.319 [info] Telemetry level is off
22:01:07.319 [info] Experiments are disabled, only manually opted experiments are active.
22:01:07.358 [debug] Start refreshing Kernel Picker (1748718067358)
22:01:07.380 [debug] Get Custom Env Variables, Class name = Mm, completed in 22ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
22:01:07.380 [debug] Jupyter Paths /kernels: 
22:01:07.380 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
22:01:07.724 [debug] End refreshing Kernel Picker (1748718067358)
22:01:07.791 [debug] KernelProvider switched kernel to id = .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher
22:01:07.792 [debug] start the kernel, options.disableUI=true for ~/Numerical_Analysis/numerical_project.ipynb
22:01:07.796 [debug] Controller selection change completed
22:01:08.072 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: "~/Numerical_Analysis", Arg 2: "RunPythonCode"
22:01:08.073 [info] Starting Kernel (Python Path: ~/Numerical_Analysis/.venv/bin/python, Venv, 3.13.3) for '~/Numerical_Analysis/numerical_project.ipynb' (disableUI=true)
22:01:08.115 [debug] Start refreshing Interpreter Kernel Picker
22:01:08.115 [debug] Start refreshing Kernel Picker (1748718068115)
22:01:08.155 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "RunPythonCode"
22:01:08.252 [debug] Launching kernel .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher for ~/Numerical_Analysis/numerical_project.ipynb in ~/Numerical_Analysis with ports 9001, 9000, 9004, 9002, 9003
22:01:08.434 [debug] Got env vars from Python Ext in 363ms for ~/Numerical_Analysis/.venv/bin/python, with env var count 71.
22:01:08.434 [debug] Getting activated env variables, Class name = xd, completed in 364ms, has a truthy return value, Arg 1: "~/Numerical_Analysis", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Arg 3: undefined
22:01:08.442 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python -m pip list
22:01:08.444 [debug] Got env vars from Python Ext in 290ms for ~/Numerical_Analysis/.venv/bin/python, with env var count 71.
22:01:08.445 [debug] Getting activated env variables, Class name = xd, completed in 290ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Arg 3: undefined
22:01:08.452 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
22:01:08.459 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python -m ipykernel_launcher --f=/run/user/1000/jupyter/runtime/kernel-v3721837b35be325722209eba05974c40fa60b18b0.json
    > cwd: ~/Numerical_Analysis
22:01:08.460 [debug] Kernel process 387349.
22:01:08.543 [debug] Refreshed Environments
22:01:08.885 [debug] Kernel output 387349: To connect another client to this kernel, use:
--existing /run/user/1000/jupyter/runtime/kernel-v3721837b35be325722209eba05974c40fa60b18b0.json
22:01:09.122 [debug] Waiting for Raw Session to be ready in postStartRawSession
22:01:09.122 [debug] Waiting for Raw session to be ready, status: connected
22:01:09.123 [debug] Waited for Raw session to be ready & got status: connected
22:01:09.123 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
22:01:09.123 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
22:01:09.123 [debug] Sending request for kernelInfo
22:01:09.127 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 4ms
22:01:09.150 [debug] Requesting Kernel info
22:01:09.154 [info] Kernel successfully started
22:01:09.156 [debug] getDataDirsImpl, Class name = Lr (started execution), Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python"
22:01:09.157 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
22:01:09.157 [debug] Jupyter Paths : 
22:01:09.158 [debug] Get Custom Env Variables, Class name = Mm, completed in 0ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "RunPythonCode"
22:01:09.159 [debug] Got env vars from Python Ext in 1ms for ~/Numerical_Analysis/.venv/bin/python, with env var count 71.
22:01:09.159 [debug] Getting activated env variables, Class name = xd, completed in 1ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Arg 3: undefined
22:01:09.166 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/pythonFiles/printJupyterDataDir.py
22:01:09.177 [debug] Got an empty Jupyter Data Dir from ~/Numerical_Analysis/.venv/bin/python, stderr = undefined
22:01:09.177 [debug] getDataDirsImpl, Class name = Lr, completed in 21ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Return Value: <Uri:~/.local/share/jupyter>, <Uri:~/Numerical_Analysis/.venv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
22:01:09.545 [debug] End refreshing Kernel Picker (1748718068115)
22:01:12.982 [debug] Handle Execution of Cells 2,4,7,10,11,14 for ~/Numerical_Analysis/numerical_project.ipynb
22:01:13.005 [debug] Kernel acknowledged execution of cell 2 @ 1748718073003
22:01:14.573 [debug] Kernel acknowledged execution of cell 4 @ 1748718074573
22:01:14.677 [debug] Kernel acknowledged execution of cell 7 @ 1748718074677
22:01:14.718 [debug] Kernel acknowledged execution of cell 10 @ 1748718074718
22:01:14.723 [debug] Kernel acknowledged execution of cell 11 @ 1748718074723
22:01:14.740 [debug] Kernel acknowledged execution of cell 14 @ 1748718074740
22:01:17.200 [debug] Handle Execution of Cells 2,4,7,10,11,14 for ~/Numerical_Analysis/numerical_project.ipynb
22:01:17.225 [debug] Kernel acknowledged execution of cell 2 @ 1748718077225
22:01:17.280 [debug] Kernel acknowledged execution of cell 4 @ 1748718077279
22:01:17.311 [debug] Kernel acknowledged execution of cell 7 @ 1748718077311
22:01:17.412 [debug] Kernel acknowledged execution of cell 10 @ 1748718077412
22:01:17.424 [debug] Kernel acknowledged execution of cell 11 @ 1748718077423
22:01:17.438 [debug] Kernel acknowledged execution of cell 14 @ 1748718077438
23:02:24.700 [debug] Jupyter completion time: 12
23:02:24.703 [debug] Execution of code ms-toolsai.jupyter-1 completed in 12ms
23:02:24.738 [debug] Inspected code def aitken_nevillnonlocal in 10ms
23:02:24.739 [debug] Execution of code ms-toolsai.jupyter-2 completed in 11ms
23:02:24.894 [debug] Inspected code def aitken_nevillnp in 7ms
23:02:24.896 [debug] Execution of code ms-toolsai.jupyter-3 completed in 9ms
23:02:25.231 [debug] Jupyter completion time: 21
23:02:25.235 [debug] Execution of code ms-toolsai.jupyter-4 completed in 25ms
23:02:25.589 [debug] Inspected code def aitken_neville(.False_ in 32ms
23:02:25.592 [debug] Execution of code ms-toolsai.jupyter-5 completed in 35ms
23:02:26.791 [debug] Jupyter completion time: 12
23:02:26.793 [debug] Execution of code ms-toolsai.jupyter-6 completed in 14ms
23:02:26.802 [debug] Inspected code def aitken_nevillnonlocal in 6ms
23:02:26.803 [debug] Execution of code ms-toolsai.jupyter-7 completed in 7ms
23:02:27.041 [debug] Inspected code def aitken_nevillnp in 11ms
23:02:27.043 [debug] Execution of code ms-toolsai.jupyter-8 completed in 12ms
23:02:27.268 [debug] Jupyter completion time: 16
23:02:27.274 [debug] Execution of code ms-toolsai.jupyter-9 completed in 21ms
23:02:29.470 [debug] Handle Execution of Cells 14 for ~/Numerical_Analysis/numerical_project.ipynb
23:02:29.496 [debug] Kernel acknowledged execution of cell 14 @ 1748721749495
23:46:34.672 [info] Dispose Kernel '~/Numerical_Analysis/numerical_project.ipynb' associated with '~/Numerical_Analysis/numerical_project.ipynb'
23:46:34.672 [debug] Cancel pending cells
23:46:34.673 [debug] Shutdown session 3c0492f0-7e7d-4e23-866a-1abb5e73b544, .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher - start called from Error: 
    at iT.shutdown (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:301:1140)
    at iT.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:301:623)
    at Is (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:115:867)
    at e (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:282:32549)
    at T_.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:282:32794)
    at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:183:1926
    at Array.map (<anonymous>)
    at Rg.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:183:1917)
    at Object.Ahe (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:447:3706)
    at Object.m (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.proxy.js:1:901)
    at PQ._deactivate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:14502)
    at file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12013
    at Array.map (<anonymous>)
    at PQ._deactivateAll (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12001)
    at PQ.terminate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12354)
    at v8.terminate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:1602)
    at ds (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:5829)
    at MessagePortMain.<anonymous> (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:2284)
    at MessagePortMain.emit (node:events:524:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
23:46:34.673 [debug] Dispose Kernel process 387349.
23:46:34.679 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/Numerical_Analysis/numerical_project.ipynb
23:46:34.683 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:46:34.683 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:46:34.684 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:46:34.684 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:46:34.684 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:46:34.685 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:46:34.685 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:46:34.685 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:46:34.685 [debug] Disposing controller .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher and documents file://~/Numerical_Analysis/numerical_project.ipynb
23:46:34.686 [debug] Disposing controller .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher 
23:46:34.692 [warn] Failed to delete connection file file:///run/user/1000/jupyter/runtime/kernel-v3721837b35be325722209eba05974c40fa60b18b0.json for pid 387349 Canceled (FileSystemError): Canceled
    at Function._handleError (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:22541)
    at Object.stat (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:19418)
    at Gc.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:236:15401)
    at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:300:469 {
  code: 'Unknown'
}
23:46:34.692 [debug] Disposed Kernel process 387349.
23:46:34.692 [debug] Shutdown session 3c0492f0-7e7d-4e23-866a-1abb5e73b544, .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher - shutdown complete
23:46:34.693 [debug] KernelProcess Exited 387349, Exit Code - null
